### ISSUE TITLE
[bug] 在小鱼吃大鱼之后再吃一只同等级的鱼会导致两条鱼覆盖为同一等级的一条鱼

### ISSUE THREAD

**Issue by hiyasame** [lomirus/shenlong-wudi-ban#1]
如题 

路哥太强了orz😭😭😭

**Comment by lomirus** [comment]
Hello, thanks for your feedback!

However, it's just a short-term project therefore here is further plan to make any improvements including bug fixes for the obfuscated code after all. But just feel free to make any pull request if you want.
